#服务端口号
server:
  port: 8000
#服务名称（注册到eureka上的服务别名）
spring:
  application:
    name: app-member
#服务注册到eureka的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
#注册到eureka
    register-with-eureka: true
#需要从eureka上获取注册信息
    fetch-registry: true